sudo: required
services:
  - docker

before_install:
  - docker build -t dhriti/docker-react -f Dockerfile.dev .

script:
  - docker run dhriti/docker-react npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  #s3 bucket name will reused for all the elasticbeanstalks that we create.
  bucket_name: "elasticbeanstalk-us-east-2-575920431687"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 